sudo: false
language: c

cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal
    - $HOME/.stack

matrix:
  include:
    - compiler: ": # Stack LTS-7 Linux"
      env: ARGS="--resolver lts-7"
      os: linux

    - compiler: ": # Stack LTS-7 OSX"
      env: ARGS="--resolver lts-7"
      os: osx

addons:
  apt:
    packages:
      - libgmp-dev

before_install:
  # Fix the build environment so we can build dependencies with gcc.
  - mkdir -p $HOME/.local/{bin,lib,share,include}
  - export CC=gcc
  - export PATH=$HOME/.local/bin:$PATH
  - export PKG_CONFIG_PATH=$HOME/.local/lib/pkgconfig:$PKG_CONFIG_PATH

  # Install ZMQ
  - wget https://github.com/zeromq/zeromq4-1/releases/download/v4.1.5/zeromq-4.1.5.tar.gz
  - tar -zxf zeromq-4.1.5.tar.gz
  - pushd zeromq-4.1.5/ && ./configure --prefix=$HOME/.local && make install && popd

  # Install Stack
  - if [ ! -f "$HOME/.local/bin/stack" ];
    then
      STACK_URL="https://www.stackage.org/stack/$TRAVIS_OS_NAME-x86_64";
      curl --location "$STACK_URL" > stack.tar.gz;
      tar --strip-components=1 -zxf stack.tar.gz;
      mv stack $HOME/.local/bin;
    fi

install:
  # Configure if need be.
  - if [ -f configure.ac ];
    then
      autoreconf -i;
    fi

  # Build.
  - stack --no-terminal --install-ghc $ARGS test --bench --only-dependencies

script:
  - stack --no-terminal $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps
