sudo: false                 # Use new container infrastructure to enable caching
language: c                 # Choose a lightweight base image; we provide our own build tools.
cache:                      # Caching so the next build will be fast too.
  directories:
    - $HOME/.ghc
    - $HOME/.cabal
    - $HOME/.stack

matrix:
  include:
    - env: ARGS="--resolver lts-7"
      compiler: "# stack-lts-7"
      addons: {apt: {packages: [ghc-8.0.1], sources: [hvr-ghc]}}

    - env: ARGS="--resolver lts-7"
      compiler: "# stack-lts-7-osx"
      os: osx

before_install:
  - |
    unset CC
    mkdir -p $HOME/.local/bin
    mkdir -p $HOME/.cabal
    export PATH=$HOME/.local/bin:$HOME/.cabal/bin:$PATH
    echo 'remote-repo: hackage.haskell.org:http://hackage.fpcomplete.com/' > $HOME/.cabal/config
    echo 'remote-repo-cache: $HOME/.cabal/packages' >> $HOME/.cabal/config
    if [ `uname` = "Darwin" ]; then
      travis_retry curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C $HOME/.local/bin
    else
      travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C $HOME/.local/bin '*/stack'
    fi
    if [ "$CABALVER" != "1.16" ]; then echo 'jobs: $ncpus' >> $HOME/.cabal/config fi
    export PACKAGES=$(stack --install-ghc query locals | grep '^ *path' | sed 's@^ *path:@@')

install: ./.travis.install
script: ./.travis.script
