sudo: false                 # Use new container infrastructure to enable caching
language: c                 # Choose a lightweight base image; we provide our own build tools.
cache:                      # Caching so the next build will be fast too.
  directories:
    - $HOME/.ghc
    - $HOME/.cabal
    - $HOME/.stack

matrix:
  include:
    - env: ARGS="--resolver lts-7"
      compiler: "# stack-lts-7"
      addons:
        apt:
          packages:
            - 'ghc-8.0.1'

          sources:
            - 'hvr-ghc'

    - env: ARGS="--resolver lts-7"
      compiler: "# stack-lts-7-osx"
      os: osx

before_install:
  - export PATH=$PWD/zeromq-4.1.5/.libs:$PATH
  - set CC=gcc
  - |
    pushd /tmp
    wget https://github.com/zeromq/zeromq4-1/releases/download/v4.1.5/zeromq-4.1.5.tar.gz -O zeromq.tar.gz
    tar -zxf zeromq.1.5.tar.gz
    pushd zeromq-4.1.5 && ./configure --prefix=/usr && make && make install && popd
    ls zeromq-4.1.5/.libs
    popd

  - |
    unset CC
    CABALARGS=""
    if [ "x$GHCVER" = "xhead" ]; then CABALARGS=--allow-newer; fi
    export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.local/bin:/opt/alex/$ALEXVER/bin:/opt/happy/$HAPPYVER/bin:$HOME/.cabal/bin:$PATH
    mkdir -p ~/.local/bin
    if [ `uname` = "Darwin" ]
    then
      travis_retry curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
    else
      travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    fi
    mkdir -p $HOME/.cabal
    echo 'remote-repo: hackage.haskell.org:http://hackage.fpcomplete.com/' > $HOME/.cabal/config
    echo 'remote-repo-cache: $HOME/.cabal/packages' >> $HOME/.cabal/config
    if [ "$CABALVER" != "1.16" ]
    then
      echo 'jobs: $ncpus' >> $HOME/.cabal/config
    fi
    PACKAGES=$(stack --install-ghc query locals | grep '^ *path' | sed 's@^ *path:@@')

install: ./.travis.install
script: ./.travis.script
