sudo: false                 # Use new container infrastructure to enable caching
language: c                 # Choose a lightweight base image; we provide our own build tools.
cache:                      # Caching so the next build will be fast too.
  directories:
    - $HOME/.ghc
    - $HOME/.cabal
    - $HOME/.stack

matrix:
  include:
    - env: ARGS="--resolver lts-7"
      compiler: "stack lts-7"
      addons: {apt: {packages: [ghc-8.0.1], sources: [hvr-ghc]}}

    - env: ARGS="--resolver lts-7"
      compiler: "stack lts-7"
      os: osx

before_install: ./.travis.before_install
install: ./.travis.install
script: ./.travis.script
