[package]
name = "Walnut"
version = "0.0.1"
authors = ["Reisen <reisen@morphism.org>"]


[dependencies.redis-rs]
#git = "https://github.com/mitsuhiko/redis-rs/"
path = "./redis-rs"


[dependencies.toml]
git = "https://github.com/alexcrichton/toml-rs"
