resolver: lts-7.0
extra-package-dbs: []
flags: {}

packages:
    - bin/walnut
    - bin/walnut-irc
    - lib/walnut-core
    - lib/walnut-binary

extra-deps:
    - monad-classes-0.3.1.1
    - peano-0.1.0.1
    - simpleirc-0.3.1
